---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran-gnb
  labels:
    app: srsran
    component: gnb
spec:
  selector:
    matchLabels:
      app: srsran
      component: gnb
  replicas: 1
  template:
    metadata:
      labels:
        app: srsran
        component: gnb
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n3network", "interface": "n3", "ips": [ "10.10.3.231/24" ] }
          ]'
    spec:
      containers:
        - image: ghcr.io/sulaimanalmani/srsranzmq/srsran_zmq:v1.0
          name: gnb
          resizePolicy:
          - resourceName: cpu
            restartPolicy: NotRequired
          resources:
            requests:
              memory: "3000Mi"
              cpu: "50m"
            limits:
              memory: "3000Mi"
              cpu: "5000m"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: SRSRAN_AMF_N3_ADDR
              value: "10.10.3.200"
            - name: SRSRAN_GNB_N3_BIND_ADDR
              value: "10.10.3.231"
            - name: SRSRAN_GNB_ZMQ_ADDR
              value: "10.10.3.231"
            - name: SRSRAN_UE_ZMQ_ADDR
              value: "10.10.3.232"
          command: ["/srsran/config/wrapper.sh"]
          volumeMounts:
            - mountPath: /srsran/config
              name: gnb-volume

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: gnb-volume
          configMap:
            name: gnb-configmap
            items:
              - key: srsran-gnb.yaml
                path: srsran-gnb.yaml
              - key: render_gnb_config.py
                path: render_gnb_config.py
                mode: 0755
              - key: capture_gnb_metrics.py
                path: capture_gnb_metrics.py
                mode: 0755
              - key: wrapper.sh
                path: wrapper.sh
                mode: 0777
              - key: start_gnb.sh
                path: start_gnb.sh
                mode: 0777
