---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran-ue1
  labels:
    app: srsran
    component: ue
    name: ue1
spec:
  selector:
    matchLabels:
      app: srsran
      component: ue
      name: ue1
  replicas: 1
  template:
    metadata:
      labels:
        app: srsran
        component: ue
        name: ue1
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n3network", "interface": "n3", "ips": [ "10.10.3.232/24" ]}
          ]'
    spec:
      runtimeClassName: nvidia
      containers:
        - image: ghcr.io/sulaimanalmani/srsranzmq/srsue:v1.1
          imagePullPolicy: Always
          name: ue
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_NICE", "IPC_LOCK", "CAP_NET_ADMIN"]
          command: ["/srsran/config/wrapper.sh"]
          env:
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/srsran/config"
            - name: SRSRAN_GNB_ZMQ_ADDR
              value: "10.10.3.231"
            - name: SRSRAN_UE_ZMQ_ADDR
              value: "10.10.3.232"
          volumeMounts:
            - mountPath: /srsran/config
              name: ue-volume
          resources:
            limits:
              nvidia.com/gpu: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: ue-volume
          configMap:
            name: ue1-configmap
            items:
              - key: radio.json
                path: radio.json
              - key: radio_endpoints.py
                path: radio_endpoints.py
              - key: multi_ue_scenario.py
                path: multi_ue_scenario.py
              - key: generate_ue_conf.py
                path: generate_ue_conf.py
              - key: wrapper.sh
                path: wrapper.sh
                mode: 0755
              - key: start_ue.sh
                path: start_ue.sh
                mode: 0755
              - key: start_gnu.sh
                path: start_gnu.sh
                mode: 0755
