apiVersion: v1
kind: PersistentVolume
metadata:
  # Legacy name for the static hostPath PV.
  name: mongodb-longhorn-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # This label must match the existing PVC.
  storageClassName: longhorn
  hostPath:
    path: /var/lib/mongo-pv/datadir-mongodb-0
    type: DirectoryOrCreate
