apiVersion: v1
kind: PersistentVolume
metadata:
  name: open5gs-mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: open5gs-local
  hostPath:
    path: /var/lib/mongo-pv/datadir-mongodb-0
    type: DirectoryOrCreate
