apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../srsue

configMapGenerator:
  - name: ue1-configmap
    behavior: merge
    files:
      - config/fixed_channel.py
      - config/channel_protocol.py
      - config/channel_control.py
      - config/multi_ue_live_channel.py
      - config/start_gnu_live_channel.sh

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: srsran-ue1
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: localhost/srsue-live:gr38-v1
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: add
        path: /spec/template/spec/containers/0/ports
        value:
          - name: channel-control
            containerPort: 5555
            protocol: TCP
          - name: channel-stream
            containerPort: 5556
            protocol: TCP
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: fixed_channel.py
          path: fixed_channel.py
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: channel_protocol.py
          path: channel_protocol.py
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: channel_control.py
          path: channel_control.py
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: multi_ue_live_channel.py
          path: multi_ue_live_channel.py
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: start_gnu_live_channel.sh
          path: start_gnu_live_channel.sh
          mode: 0755
