apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply the matching two-antenna gNB overlay.
resources:
  - ../srsue-live

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: srsran-ue1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SRSRAN_GNB_ANTENNAS
          value: "2"
