amf:
  addr: ${SRSRAN_AMF_N3_ADDR}
  bind_addr: ${SRSRAN_GNB_N3_BIND_ADDR}

ru_sdr:
  device_driver: zmq
  device_args: ${SRSRAN_ZMQ_GNB_DEVICE_ARGS}
  srate: 23.04
  tx_gain: 75
  rx_gain: 75

cell_cfg:
  dl_arfcn: 368500
  band: 3
  channel_bandwidth_MHz: 20
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  common_scs: 15
  plmn: "00101"
  tac: 7
  pdcch:
    common:
      ss0_index: 0
      coreset0_index: 12
    dedicated:
      ss2_type: common
      dci_format_0_1_and_1_1: false
  prach:
    prach_config_index: 1
    total_nof_ra_preambles: 63

slicing:
  - sst: 1
    sd: 000001
  - sst: 2
    sd: 000002
